//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod msg_channel;
pub mod msg_delivery;
pub mod msg_delivery_channel;
pub mod msg_delivery_channel_log;
pub mod msg_delivery_target;
pub mod msg_message;
pub mod msg_message_category;
pub mod msg_message_channel;
pub mod msg_message_level;
pub mod msg_message_source;
pub mod msg_message_target;
pub mod msg_target_category;