//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "msg_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub category_id: Option<i64>,
    pub mes_id: i64,
    pub source_id: Option<i64>,
    #[sea_orm(unique)]
    pub code: String,
    #[sea_orm(unique)]
    pub name: String,
    pub title_template: String,
    pub content_template: String,
    pub remark: Option<String>,
    pub persisted: bool,
    pub enabled: bool,
    pub creator_id: i64,
    pub create_ms: i64,
    pub updator_id: i64,
    pub update_ms: i64,
    #[sea_orm(
        belongs_to,
        from = "mes_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub msg_message_level: BelongsTo<super::msg_message_level::Entity>,
    #[sea_orm(has_many)]
    pub msg_message_channels: HasMany<super::msg_message_channel::Entity>,
    #[sea_orm(has_many)]
    pub msg_message_targets: HasMany<super::msg_message_target::Entity>,
    #[sea_orm(has_many)]
    pub msg_deliveries: HasMany<super::msg_delivery::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}