//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "msg_delivery_target")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub delivery_id: i64,
    pub target_category_id: i64,
    pub target_id: Option<i64>,
    pub deliver_target_status: i16,
    pub creator_id: i64,
    pub create_ms: i64,
    pub updator_id: i64,
    pub update_ms: i64,
    #[sea_orm(
        belongs_to,
        from = "delivery_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub msg_delivery: BelongsTo<super::msg_delivery::Entity>,
    #[sea_orm(has_many)]
    pub msg_delivery_channels: HasMany<super::msg_delivery_channel::Entity>,
    #[sea_orm(
        belongs_to,
        from = "target_category_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub msg_target_category: BelongsTo<super::msg_target_category::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
