//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "msg_delivery")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub message_id: i64,
    #[sea_orm(unique)]
    pub business_id: i64,
    pub deliver_status: i16,
    pub title: String,
    pub content: String,
    pub remark: Option<String>,
    pub creator_id: i64,
    pub create_ms: i64,
    pub updator_id: i64,
    pub update_ms: i64,
    #[sea_orm(
        belongs_to,
        from = "message_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub msg_message: BelongsTo<super::msg_message::Entity>,
    #[sea_orm(has_many)]
    pub msg_delivery_targets: HasMany<super::msg_delivery_target::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}