//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "msg_delivery_channel_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub delivery_channel_id: i64,
    pub deliver_channel_status: i16,
    pub address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub detail: Option<String>,
    pub creator_id: i64,
    pub create_ms: i64,
    pub updator_id: i64,
    pub update_ms: i64,
    #[sea_orm(
        belongs_to,
        from = "delivery_channel_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub msg_delivery_channel: BelongsTo<super::msg_delivery_channel::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
