//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "msg_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub options: Option<String>,
    pub remark: Option<String>,
    pub enabled: bool,
    pub creator_id: i64,
    pub create_ms: i64,
    pub updator_id: i64,
    pub update_ms: i64,
    #[sea_orm(has_many)]
    pub msg_delivery_channels: HasMany<super::msg_delivery_channel::Entity>,
    #[sea_orm(has_many)]
    pub msg_message_channels: HasMany<super::msg_message_channel::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
