[workspace]
members = ["msg-api", "msg-api-client", "msg-svr", "msg-pub"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.104"
log = "0.4.34"
tracing = "0.1.44"
clap = "4.6.6"
chrono = "0.4.45"
config = "0.15.25"
derive_setters = "0.1.9"
typed-builder = "0.23.2"
arc-swap = "1.9.2"
async-trait = "0.1.92"
serde = "1.0.229"
serde_with = "3.23.0"
serde_json = "1.0.151"
reqwest = "0.13.5"
tokio = "1.53.1"
tokio-util = "0.7.19"
axum = "0.8.9"
sqlx = "0.9.0"
sea-orm = "2.0.2"
linkme = "0.3.37"
regex = "1.13.1"
o2o = "0.5.5"
validator = "0.21.0"
strum = "0.28.0"
utoipa = "5.5.0"
utoipa-swagger-ui = "9.0.2"
humantime = "2.4.0"
redis = "1.7.0"
async-nats = "0.50.0"
bytes = "1.12.1"
futures = "0.3.34"


idworker = "1.3.0"
wheel-rs = "1.12.0"
robotech = "1.16.0"
robotech-macros = "1.16.0"
msg-api = { version = "1.0.0", path = "./msg-api" }
msg-api-client = { version = "1.0.0", path = "./msg-api-client" }

[patch.crates-io]
wheel-rs = { path = "../wheel-rs" }
robotech = { path = "../robotech-rs/robotech" }
robotech-macros = { path = "../robotech-rs/robotech-macros" }
msg-api = { path = "./msg-api" }
msg-api-client = { path = "./msg-api-client" }