[package]
name = "msg-api-client"
version = "1.0.0"
edition = "2024"
authors = ["zbz"]
license = "MIT"
keywords = ["msg", "api-client", "client"]
description = "API client for MSG, a general message center system"
categories = ["web-programming::http-server"]
homepage = "https://github.com/rusthing/msg"
repository = "https://github.com/rusthing/msg"
readme = "README.md"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
arc-swap = { workspace = true }
config = { workspace = true }
reqwest = { workspace = true, features = ["multipart", "json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras"] }

wheel-rs = { workspace = true }
robotech = { workspace = true, features = ["feign", "macros", "registry-center"] }
msg-api = { workspace = true }