level = "debug"

[modules]
"h2::codec" = "info"
"h2::proto" = "info"
"tower::buffer" = "info"
"hyper_util::client" = "info"
"reqwest::connect" = "info"
"robotech::cfg::cfg_utils" = "error"
"robotech::micro_svc::hub_client::hub_client" = "error"